# nginx.yml
---
- hosts: nginx
  remote_user: ubuntu
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: true

    - name: Install required packages
      apt: name=nginx
      become: true
