# web.yml
---
- hosts: all
  roles:
    - sprylab.tomcat-ubuntu 
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: true

    - name: Install required packages
      apt: name={{ item }}
      become: true
      with_items:
        - nginx
        - postgresql
