- hosts: all
  gather_facts: False
  remote_user: ubuntu
  tasks:
  - name: Installing python
    delegate_to: special_host_name
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
